name: Secure Port Scanner (Push to Private Repo)

on:
  workflow_dispatch: # 支持手动点击测试
  schedule:
    - cron: '0 0 */7 * *' # 每 7 天自动运行一次

jobs:
  secure_scan:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出当前扫描仓库代码
    - name: Checkout code
      uses: actions/checkout@v5

    # 2. 安装 Nmap 工具
    - name: Install Nmap Tool
      run: |
        sudo apt-get update
        sudo apt-get install -y nmap

    # 3. 极速全端口嗅探
    - name: Run Full Port Nmap Scan (0-65535)
      env:
        MY_TARGET_IP: ${{ secrets.MY_SERVER }}
      run: |
        nmap -p- -T4 --min-rate 1500 $MY_TARGET_IP > nmap_report.txt

    # 4. 运行解析验证脚本，产出 report.json
    - name: Process & Generate JSON Report
      env:
        MY_USER: ${{ secrets.MY_USER }}
        MY_PASS: ${{ secrets.MY_PASS }}
      run: python ${{ github.workspace }}/send_nmap.py

    # 5. 将生成的 report.json 跨仓库安全投递到你的【私密仓库】中
    - name: Pushing report to Private Repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        # 🎯 核心修复：这里改成你在第一步里刚刚设置好的新名字 MY_PAT
        API_TOKEN_GITHUB: ${{ secrets.MY_SECPAT }}
      with:
        source-directory: '.'
        file-name: 'report.json'
        # 👤 填入你的 GitHub 真实用户名
        destination-github-username: 'yaslanglobal-oss'
        # 🔒 填入你刚才建立的【私密仓库】的名称
        destination-repository-name: 'mypr0xy'
        user-email: 'github-actions[bot]@://github.com'
        target-branch: 'main'
        commit-message: '自动同步：定时全端口审查报告更新'
